
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[workspace]
resolver = "2"
members = ["bytepiece", "bytepiece_rs"]


[workspace.dependencies]
bytepiece = { path = "bytepiece" }
